### ISSUE TITLE
请教如何修改下面的警告

### ISSUE THREAD

**Issue by xoming** [node-weixin/node-weixin-menu#1]
You must register a new get function with node-weixin-settings,

**Comment by calidion** [comment]
settings与session实际使用时都需要重写自己的get, set.
也就是调用

```
registerSet
registerGet
registerAll
```

这两个函数来注册新的get/set方法。
参考这里的代码：
https://github.com/node-weixin/node-weixin-express/blob/master/lib/mySettings.js
https://github.com/node-weixin/node-weixin-express/blob/master/lib/mySession.js
如果是测试可以忽略。

**Comment by xoming** [comment]
谢谢，你讲的思路明白了。打开下面的链接报404错误，能重新发个地址吗？3Q:)
https://github.com/node-weixin/node-weixin-express/blob/master/lib/mySettings.js
https://github.com/node-weixin/node-weixin-express/blob/master/lib/mySession.js

**Comment by xoming** [comment]
谢谢，已经找到了，不用回复:)
