### ISSUE TITLE
这个项目确定是完工的？

### ISSUE THREAD

**Issue by yufeikang** [node-weixin/node-weixin-menu#3]
cli 是完全注释掉的！
![image](https://user-images.githubusercontent.com/4519880/47073727-7e592c00-d22b-11e8-9010-693d70407d71.png)

例子也是无法使用，看代码参数个数都不一致

**Comment by calidion** [comment]
这个项目已经完成很久了。如果有API的变更，欢迎提交pr.

**Comment by yufeikang** [comment]
感觉不像的，代码里的逻辑是错的，不是api变动啊。抽空我来改一版吧
